---
{{ if eq .Values.env "dev" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dino-park-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: dinopark.mozilla.community
    http:
      paths:
      - path: /
        backend:
          serviceName: dino-park-mozillians-service
          servicePort: 80
      - path: /beta/js
        backend:
          serviceName: dino-park-front-end-service
          servicePort: 80
      - path: /beta/css
        backend:
          serviceName: dino-park-front-end-service
          servicePort: 80
      - path: /beta/img
        backend:
          serviceName: dino-park-front-end-service
          servicePort: 80
{{ end }}
